#task_1

In [21]:
import numpy as np

In [1]:
from numpy import random

In [3]:
x = random.randint(100,size=(4,4))

print(x)

[[ 8  2 37 91]
 [61 58  2 93]
 [83 28 72 29]
 [36 32 23 32]]


In [4]:
import pandas as pd

In [5]:
df=pd.DataFrame(x)

In [6]:
df

0   1   2   3
0   8   2  37  91
1  61  58   2  93
2  83  28  72  29
3  36  32  23  32

#task_2

In [7]:
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']

In [8]:
df

Random value 1  Random value 2  Random value 3  Random value 4
0               8               2              37              91
1              61              58               2              93
2              83              28              72              29
3              36              32              23              32

#task_3

In [9]:
df.describe()

Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean        47.000000       30.000000       33.500000       61.250000
std         32.321304       22.920151       29.422214       35.537539
min          8.000000        2.000000        2.000000       29.000000
25%         29.000000       21.500000       17.750000       31.250000
50%         48.500000       30.000000       30.000000       61.500000
75%         66.500000       38.500000       45.750000       91.500000
max         83.000000       58.000000       72.000000       93.000000

#task_4

In [10]:
df.isnull().any()

Random value 1    False
Random value 2    False
Random value 3    False
Random value 4    False
dtype: bool

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      int64
 1   Random value 2  4 non-null      int64
 2   Random value 3  4 non-null      int64
 3   Random value 4  4 non-null      int64
dtypes: int64(4)
memory usage: 256.0 bytes


task_5

In [20]:
df.loc[:,'Random value 2':'Random value 3']

Random value 2  Random value 3
0               2              37
1              58               2
2              28              72
3              32              23

In [13]:
df.iloc[:,1:3]

Random value 2  Random value 3
0               2              37
1              58               2
2              28              72
3              32              23